# Created by: Pawel Pekala <c0rn@o2.pl>
# $FreeBSD$

PORTNAME=	notification
PORTREVISION=	0

COMMENT=	New mail notification plugin for Claws Mail

LIB_DEPENDS=	libnotify.so:devel/libnotify

USES=		canberra:gtk2

CLAWS_PLUGINS_BUILD=	notification

.include "../claws-mail/Makefile.claws"
.include <bsd.port.mk>
