# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD$

PORTREVISION=		0
CATEGORIES=		graphics python
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

COMMENT=		OpenCV Python library

MASTERDIR=		${.CURDIR:H}/opencv
PLIST=			${.CURDIR}/pkg-plist

_OPENCV_PACKAGE=	python

.include "${MASTERDIR}/Makefile"
