# $FreeBSD$

PORTREVISION=		0
CATEGORIES=		graphics java
PKGNAMESUFFIX=		-java

COMMENT=		OpenCV JAva library

MASTERDIR=		${.CURDIR:H}/opencv
PLIST=			${.CURDIR}/pkg-plist

_OPENCV_PACKAGE=	java

.include "${MASTERDIR}/Makefile"
