# $FreeBSD$

PORTNAME=	texlive-collection-games
DISTVERSION=	20200406
CATEGORIES=	print
MASTER_SITES=	ftp://ftp.tug.org/historic/systems/texlive/2020/
DISTFILES=	texlive-${DISTVERSION}-texmf${EXTRACT_SUFX}
DIST_SUBDIR=	TeX

MAINTAINER=	latex@FreeBSD.org
COMMENT=	TeX Live Typesetting System, texmf Tree

USES=		python:run shebangfix tar:xz texlive

.include <bsd.port.mk>
